---
  title: "Group dynamics"
---
  
```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```

### Policies

Your group has a number of responsibilities for problem and project assignments, described below.

- Designate a coordinator, recorder, reproducibility checker, and monitor/reviewer for each assignment. These should vary so that each group member takes a different role on a new assignment. For 5-person teams, split the roles of reviewer and monitor.
- Agree on meeting times in advance and on what each member should have complete before the meetings (readings, initial analysis, coding, etc.).
- Do the required individual preparation.
- Coordinator sends reminder before meeting that includes meeting location, time, and individual preparation assignments
- Meet and work. Coordinator keeps everyone on task and makes sure everyone is involved, recorder prepares final solution to be turned in, monitor makes sure everyone understands the solution, including the coding, the checker double-checks the work for reproducibility (and errors!), and the reviewer is responsible for (1) sharing comments on the graded project (and interim submissions) with the team (2) leading a discussion about them, with a focus on how to improve moving forward, and (3) reviewing effort apportionment in a constructive conversation with the team.
- Checker turns in assignment, which also indicates which student took on each role in the first bullet point.
- All team members complete written evaluations of effort put forth by other team members.
- Reviewer coordinates review of returned assignments.

### Team expectations agreement

On a single sheet of paper, list the names of all group members along with a list of expectations the team wishes to adopt.  Suggestions are below, but you can add or subtract any items as needed. Each member should sign the sheet and turn it in on class September 4.

Potential expectations include the following (not an exhaustive list!):

- Make a serious effort at assigned work before meetings
- Make sure anyone who misses a meeting for a good cause gets caught up on progress
- Attend meetings
- Show up on time and stay for full meeting
- Notify project coordinator as soon as possible if unable to attend a meeting or fulfill a responsibility
- Listen thoughtfully to all team members
- Follow up promptly on assigned tasks
- Complete high quality work
- Discuss team-related issues frankly and honestly with the group
- Occasionally bring cookies or donuts to meetings
- Never bring smelly food to meetings
- Skype into meetings if you are sick rather than communicating a communicable disease
- You get the picture!



<tiny> Group policies adapted from Felder and Brent, 2000 </tiny>

### Group evaluations

After each group activity (lab report or case study), each group member will provide the following on Sakai.

(1) A list of all other team members (not including you) and considering all the work on the assignment that was not done by you, a breakdown of the fraction of work done by each other team member. For example, if you are on a 4 person team and the other team members all contributed equally, you'd assign the fraction 1/3 to each of them (regardless of whether you all did 1/4 of the work overall, or whether you personally did half the work and the others each did 1/6).
(2) In the case you feel one or more team members deserves a different grade on the assignment than the others, you'll provide a description of why that member or members deserves a different grade. (In this case you can talk about your own relative contribution.)

A concern or complaint of unequal division of labor within a group that is not accompanied by group evaluations indicating this will generally not be entertained.

At any time a group can request a meeting with the instructor to discuss group dynamics or other challenges.