---
title: " "
output: 
  html_document:
    toc_float: true
  
---

---
title: "STA 410/610: Multilevel and Hierarchical Models"
description: "Variance component models with fixed and random effects. Multilevel and hierarchical models for longitudinal and/or clustered data. Focus on model fitting and interpretation. Maximum likelihood and Bayesian inference and computation. Prerequisite: STA 360/601/602 and R programming skills. QS."
markup: "mmark"
---



#Welcome to STA410/610!

### Class Meetings

<font color="#6CA0DC"><i class="fas fa-university fa-lg"></i></font> &nbsp; Old Chem 116

<font color="#6CA0DC"><i class="fas fa-calendar-alt fa-lg"></i></font> &nbsp; MWF 11:45 - 1:00 (usually Mondays will be labs, but sometimes lab and lecture will be swapped)


### Teaching team and office hours 


Note: office hours may vary due to travel and other commitments. Revisions to office hours will be noted via e-mail and on my office door. 

| Team member | Office hours | Location |
| ----------  | -------------------------------------         | ---- |
| [Professor Amy Herring](https://stat.duke.edu/people/amy-h-herring)  <a href="mailto:amy.herring@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | Wednesday and Thursday 1:45-2:45pm | 208 Old Chemistry |
 [TA Xu Chen](https://stat.duke.edu/people/xu-chen)  <a href="mailto:xu.chen2@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | Friday 1:30-3:30 | 025 Old Chemistry
 [TA Isaac Lavine](https://stat.duke.edu/people/isaac-lavine)  <a href="mailto:isaac.lavinei@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp; | Monday 9:00-10:00am and 2:00-3:00pm | 203B Old Chemistry
 
                  


### Materials

You should have access to a laptop and bring it to every class, fully charged. Texts and readings will be assigned as needed. The instructor and TA's will support computation in R/RStudio. 

Helpful resource materials for the course include the following.

- Hoff, CSSS - Statistics 560 Lecture notes (Sakai)

- [Gelman and Hill, Data Analysis Using Regression and Multilevel/Hierarchical Models](https://www.amazon.com/Analysis-Regression-Multilevel-Hierarchical-Models/dp/052168689X)


### Topics and Important Dates

STA 410/610 contain a mixture of lecture, lab, and combination sessions at the usual class and lab times. Frequent mini-assessments will be provided in class and lab to check mastery and identify areas for additional focus.

Note: this schedule is approximate and is likely to be modified as the course progresses. Some lab sessions will be swapped with lectures due to instructor travel or course timing. Assignments are due at the beginning of class unless otherwise specified. 



|Date           |Topic                      |Deliverables     |
| ----------    | ---------------------------         | --------------- |
| August 26     | Welcome and Introductions        | ANOVA warm-up (in class)        |
| August 28     | One Way ANOVA: Scalar and Matrix Formulations    |   Getting to Know You Sheet              |
| August 30     |  MLE's, Contrasts, Coding Schemes, and Interaction      |    Scientific Writing: ANOVA Results (in class)     |
| September 2    |  Lab: Hands-on with ANOVA     |  Group Lab Reports      |
| September 4   | Random Effects ANOVA | Group Policies Document Due |
| September 6   | Random Effects ANOVA|  |
| September 9  | Bayesian Estimation | Assignment 1 Due  |
| September 11  | Lab: Visualizing Estimates  | Group Lab Reports   |
| September 13  |Bayesian Estimation |  |
| September 16  | Lab: Empirical Bayes \& Bayesian Estimation | Group Lab Reports   |
| September 18  | Random Effects ANCOVA |   |
| September 20  | Linear Mixed Effects Model and Case Study 1 Introduction | Assignment 2 Due  |
| September 23  | Lab: Fitting Hierarchical Bayes Models | Group Lab Reports  |
| September 25  | Exam Review |  |
| September 27  | Exam 1 (in class)  | Exam 1 (in class) |
| September 30  |  Lab: Linear Mixed Effects Models I         | Group Lab Reports  |
| October 2     | Estimation in LME | Exam 1 Returned (my deliverable)  | 
| October 4     | Lab: Help, I'm Behind! Hands-on Analysis and Q&A | Midsemester Grades Due (my deliverable)  |
| October 7    | Fall break  |  |
| October 9    |  Hierarchical Models with Nonconstant Variance |  |
| October 11    | Linear Mixed Effects Model for Longitudinal Data |   |
| October 14    | Lab: Longitudinal Data Analysis | Group Lab Reports  |
| October 16    | Linear Mixed Effects Model for Longitudinal Data |  |
| October 18    | Case Study Presentations |  Case Study 1 Due |
| October 21    | Lab: Logistic Regression | Group Lab Reports  | 
| October 23    | Case Study Presentations | |
| October 25    | Generalized Linear Models  |  | 
| October 28    | Lab: Mixed Effects  | Assignment 3 Due; Group Lab Reports  | 
| October 30    | Bayesian Estimation of GLM and Case Study 2 Introduction  |    |
| November 1    | Generalized Linear Mixed Effects Models |  |
| November 4    | Lab: Hierarchical Logistic Regression | Group Lab Reports  | 
| November 6    | Bayesian Estimation of GLMM |  |
| November 8    | GLMM in Practice  |  |
| November 11   | Lab: Bayesian GLMM | Group Lab Reports  |
| November 13   | Bayesian Estimation with Missing Data |  |
| November 15   | Bayesian Estimation with Missing Data | Assignment 4 Due |
| November 18   | Lab: Estimation with Missing Data | Group Lab Reports  |
| November 20   | Bayesian Estimation with Missing Data |  | 
| November 22   | Lab: Exam Review |  |
| November 25   | Exam 2 (in class) | Exam 2 (in class) |
| December 2    | Make-Up Day (exam/assignment replacement opportunity) |  |
| December 4    | Case Study 2 Presentations | Case Study 2 Due |
| December 6    | Case Study 2 Presentations |  |


