---
title: "Policies"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```




###Diversity & inclusiveness

The Duke University Community Commitment states: "Because diversity is essential to fulfilling the university’s mission, Duke is committed to building an inclusive and diverse university community.  Every student, faculty, and staff member —whatever their race, gender, age, ethnicity, cultural heritage or nationality; religious or political beliefs; sexual orientation or gender identity; or socioeconomic, veteran or ability status—has the right to inclusion, respect, agency and voice in the Duke community.  Further, all members of the University community have a responsibility to uphold these values and actively foster full participation in university life."

It is my goal for our learning environment to facilitate learning and intellectual development for everyone. To help accomplish this:
  
  - If you have a name and/or set of pronouns that differ from those that appear in your official Duke records, please let me know.
  - We are constantly learning more about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. 
  

### Academic integrity

Duke University is a community dedicated to scholarship, leadership, and service and to the principles of honesty, fairness, respect, and accountability. Citizens of this community commit to reflect upon and uphold these principles in all academic and nonacademic endeavors, and to protect and promote a culture of integrity.

Remember the Duke Community Standard that you have agreed to abide by:
  
To uphold the Duke Community Standard:
  
- I will not lie, cheat, or steal in my academic endeavors;
- I will conduct myself honorably in all my endeavors; and
- I will act if the Standard is compromised.

Cheating or plagiarism on assignments, lying about an illness or absence and other forms of academic dishonesty are a breach of trust with classmates and faculty, violate the <a href="http://www.studentaffairs.duke.edu/conduct/resources/dcs">Duke Community Standard</a>, and will not be tolerated. Such incidences will result in a 0 grade.  Additionally, there may be penalties to your final class grade along with being reported to the <a href="http://www.studentaffairs.duke.edu/conduct/about/ucbhearings">Undergraduate Conduct Board</a> (undergraduates) or relevant Director of Graduate Studies (graduate students).

Please review the Academic Dishonesty policies <a href="https://studentaffairs.duke.edu/conduct">here</a>. 

- Several datasets we are privileged to use in class are confidential and cannot be distributed more broadly. Further dissemination of such datasets, made available on Sakai, will be considered a violation of the Duke Community Standard. If you are unsure whether you can use a dataset for purposes beyond class, please ask me.

- Much of the work assigned in class is collaborative. The individual case study must be completed independently. In addition, regular assessments must be completed individually before they are tackled by the group. 

**Referencing code:** The web contains an enormous volume of code that you may find useful. You are welcome to make use of any online resources (e.g. StackOverflow), but you must explicitly cite your sources. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. On the individual case study you may not directly share code with another student in this class, and on team assignments you may not share code with another team in this class (you are welcome to discuss the problems together and ask for advice, but you may not send or make use of code from another team). 

### Course components

#### Class sessions

If you miss class or would like to review the material covered in class, you can [view the recordings](https://trinity.capture.duke.edu/Panopto/Pages/Sessions/List.aspx?folderID=735bff35-7bfa-4d15-a407-a94a00e1ff40). Note that you will need to log in with your Net ID.

#### Teams

On the first day of class, we will develop teams of 5-7 students - these teams will stay consistent 
throughout the semester (barring extraordinary circumstances). You will work in these teams during 
class and on the five group case studies. The process of forming teams will be completely transparent 
and based on self-reported data. Groups should adhere to specified [group policies](grouppolicies.html).

#### Case studies

STA 440 involves detailed analysis of a series of case studies using current, relevant data. Each case study will involve a final submission and in some cases one or more interim submissions. Points will be allocated separately for each submission and case study based on the scope of work. Final case study submissions will involve a written report and possibly an oral presentation to be viewed by the other teams (in class or by video, as assigned). 

Additional details on the case studies will be provided as the course progresses.

Individual contributions to each submission will be assessed using the fair division software [Spliddit](http://www.spliddit.org). Team members must provide Spliddit assessments in order to receive credit for an assignment.

Each individual case study will be graded based on written reports (interim and final) and an oral presentation. Students may not collaborate with anyone on the individual case study, which should be treated like a take-home exam.

Each case study will have a page limit, and under no circumstances should font sizes less than 11 point be used, with the exception of labels in figures (and then only if they are still clearly legible to readers of all ages).

#### Application exercises

Short exercises will frequently be administered at the begininning of class to assess progress and identify areas for further development. Students will first complete these individually and hand them in; subsequently, the group will discuss the exercise and turn in a group solution. 

Students who miss individual and group submissions (due to late arrival or absence) will receive 0 points for those submissions. However, only the top 80% of submissions (separately for individual and group submissions) will count towards a student's point total.


### Grading

Your final grade will be comprised of the following:

|Component | % of Grade |
| ----------    | -----------------  |     
|Individual exercises      | 10% |
|Group exercises       | 15% |
|Group case studies            | 60% |
|Individual case study        | 15% |

Class attendance is a firm expectation; frequent absences or late arrivals are a legitimate cause for grade reduction.

Cumulative numerical averages of 90 - 100 are guaranteed at least an A-, 80 - 89 at least a B-, and 70 - 79 at least a C-; however, the exact ranges for letter grades will be determined at the end of the semester. The more evidence there is that the class is performing at the highest level, the higher the grade distribution will be.

The grade for each group case study submission will be based on two components: (1) an overall score, $s_{ik}$, assigned to the work for group $k$ on case study $i$ submitted out of 100 possible points, and (2) individual contribution to the work (as assessed by team members on Spliddit). Each team member's grade on each submission will be determined by taking the total number of team points available (points $s_i$ earned for the assignment multiplied by $N_k$, the number of team members) and assigning them proportionately to team members' assessments of the division of work.  

Example:  Suppose a submission is worth 100 points, and the team has 5 members. If group k's score $s_k=90$, and all 5 team members contribute equally (20\% of the work each), then 450 points are available for allocation, and each team member receives 450/5=90 points for the submission.  If the contributions of the team members are (35\%, 30\%, 20\%, 10\%, 5\%), then their respective grades are 157.5, 135, 90, 45, and 22.5 (i.e., 7 times the work yields 7 times the points).

The total number of group project points over the course of the semester for team $k$ is $T_k=N_k\sum_{i=1}^5 s_{ik}$, and the maximum number of points that will be awarded to any team member in total for group projects is 500. This ensures (1) team members are able to adjust their effort levels on projects according to their interests and other time commitments, (2) teams are encouraged to ensure contributions over the course of the semester are balanced across team members, and (3) individuals who do not make strong contributions to the team will receive clear feedback regarding the need for adjustments to their efforts. 

### Accommodations

- Students who need accommodations in this class should contact the [Student Disability Access Office](http://access.duke.edu/students/) as soon as possible to ensure appropriate accommodations can be made.

### Excused absences

Students who miss a class due to a scheduled varsity trip, religious holiday, or short-term illness should fill out an online <a href="https://trinity.duke.edu/undergraduate/academic-policies/athletic-varsity-participation">NOVAP</a>, <a href="https://trinity.duke.edu/undergraduate/academic-policies/religious-holidays">RHoliday</a> or <a href="http://trinity.duke.edu/academic-requirements?p=policy-short-term-illness-notification">short-term illness</a> form respectively. Note that these excused absences do not excuse you from assigned case studies; it is your responsibility to make alternative arrangements with your team to participate.

If you are faced with a personal or family emergency or a
chronic health condition that interferes with your ability to attend or 
complete classes, you should contact your academic dean’s office (undergraduate) or the Director of Graduate Studies in your department (graduate). See more 
information on policies surrounding these conditions 
at https://trinity.duke.edu/undergraduate/academic-policies/personal-emergencies. 




### Late / missed work

Late work policy for case study reports: 

- late, but within 24 hours of due date/time: -20%
- any later: no credit
- Late work will not be accepted for the election case study November 5 submission or the individual case study
- Missed application exercises cannot be made up (the bottom 20% will be dropped anyway)
- You must complete the individual case study and be in class to present it in order to pass this course.

### Regrade requests

Regrade requests must be made within three days of when a report is returned. These will be honored if points were tallied incorrectly, or if you feel part of your report is correct, but it was marked wrong. No regrade will be made to alter the number of points deducted for an issue. There will be no grade changes after the individual project presentations.



### Professionalism

- Please refrain from texting or using your computer for anything other than coursework during class.


