---
title: "Lab 5: Who Votes in NC?"
---

## Who votes in NC?

When predicting election outcomes, it is important to take into account the demographic profile (with respect to demographics that vary in support of candidates) of voters. In this lab you'll explore who votes in NC.

## 2010 Census

The 2010 Census data are available under Resources on Sakai. The Census presents information on the following variables.

- County
- Age (18-25, 26-40, 41-65, 66+)
- Gender (Female, Male)
- Hispanic ethnicity (Yes, No)
- Race (Only American Indian/Alaska Native, Only Asian, Only Black, Only Native Hawaiian or Other Pacific Islander, Only White, Only Some Other Race, Multiracial)
- Population counts for each combination of the above variables

## Voting Data

Sakai also contains the data from NC on who voted in the November 8, 2016 election. (Note: other voting data are available from NC at the links provided in the case study description.)  These variables include the following. The data dictionary on Sakai contains keys to the variables. For this case study, just focus on county, race, ethnicity, gender, and age. 

- County (where someone voted)
- Party Identification (membership only, not how they voted, coded as Democrat, Libertarian, Republican, or Unaffiliated)
- Race (Black, American Indian/Alaska Native, Other, White, Undesignated, Asian, Multiracial)
- Ethnicity (Hispanic/Latino, Not Hispanic/Latino, Undesignated)
- Gender (Female, Male, Undesignated)
- Age (18-25, 26-40, 41-65, 66+)
- Number of voters for each combination of the above variables

## Your job!

Fit a model to determine (a) factors predictive of voting in NC, and (b) obtain best predictions of the probability of voting in each combination of the groupings above. The Census data provide information on who lives in each county, and the voter files show who voted in the last election. The data do not contain information on the number of registered voters by party in each county -- bonus points for adding that data to the analysis if you can get it!  You can find [data resources online](https://vt.ncsbe.gov/RegStat/Results/?date=10%2F26%2F2019) -- this linked one is a little coarse so perhaps you can do better!

This lab will be due on Wednesday, November 13.

